### PR TITLE
Shaping the project structure

### PR DESCRIPTION
**Pull request by XiaoXuxxxx**
For now, we use...
- [x] [fiber](https://github.com/gofiber/fiber) for HTTP server
- [x] [validator](https://github.com/go-playground/validator) for incoming request payload
- [x] [zap](https://github.com/uber-go/zap) for logging
- [x] Use MySQL for database, [gorm](https://github.com/go-gorm/gorm) for orm
- [x] Use [viper](https://github.com/spf13/viper) for reading config

The code is not final yet, this PR is just about the project structure only. And for sure!!! we use clean architecture for project structure.

### CODE REVIEW

**Comment by Porping** [comment]
LGTM 
`

**Comment by eltfshr** [comment]
LGTM 😈.
I'll study everything from the list

**Comment by XiaoXuxxxx** [comment]
@Porping @eltfshr

Suppose you want to add or remove tools. or if you see something wrong or want to improve the project structure. Please don't hesitate to make any changes na kub.

**Review by Porping — APPROVED** [review]

**Review by eltfshr — APPROVED** [review]
💯 👌

**Pull request merged**
